---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-b
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ssd-storage-class
  local:
    path: /nvme/data/pv-b
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: ssd
          operator: In
          values:
          - "true"