---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: ssd-storage-class
provisioner: kubernetes.io/no-provisioner
volumeBindingMode: WaitForFirstConsumer
allowedTopologies:
- matchLabelExpressions:
  - key: ssd
    values:
    - "true"
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: persistent-volume-a
spec:
  capacity:
    storage: 10Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: ssd-storage-class
  local:
    path: /nvme/data/pv-a
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: ssd
          operator: In
          values:
          - "true"