apiVersion: metallb.io/v1beta1
kind: L2Advertisement
metadata:
  name: main-advertisement
  namespace: metallb-system
spec:
  ipAddressPools:
  - main-pool
  nodeSelectors:
  - matchLabels:
      kubernetes.io/hostname: legolas